# Constants for game mechanics

ARENA_SIZE = 3000
MIN_SHIP_SEPARATION = ARENA_SIZE // 4
CENTER_BUFFER = ARENA_SIZE // 4

SPEED_SCALE = 1.0
TURN_WAIT_SCALE = 2
THRUST_WAIT_SCALE = 2

GRAVITY_MULTIPLIER = 000
STAR_COUNT = int(ARENA_SIZE*ARENA_SIZE*0.00001)

SPEED_LIMIT = 500